name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'


jobs:
  run_unittest_tests:
    name: Unittest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version:
            - "3.10"
            - "3.11"
            - "3.12"
        django-version:
            - "5.0"
            - "5.1"
            - "main"
        exclude:
            - python-version: "3.10"
              django-version: "main"
            - python-version: "3.11"
              django-version: "main"

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install --upgrade setuptools
          pip install tox

      - name: Run unittest Python ${{ matrix.python-version }} -- Django ${{ matrix.django-version }}
        env:
          TOXENV: py${{ matrix.python-version }}-django${{ matrix.django-version }}
        run: tox

  run_quality_tests:
    name: Quality tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          pip install tox

      - name: Quality tests
        env:
          TOXENV: ruff
        run: |
          tox